/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/register-person": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterPerson"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rename-person": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RenamePerson"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/change-person-contact-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePersonContactDetails"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/change-person-club-affiliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePersonClubAffiliation"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/link-sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LinkSignIn"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grant-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GrantRole"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revoke-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RevokeRole"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configure-capture-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfigureCapturePolicy"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bind-identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BindIdentity"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publish-class-definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PublishClassDefinition"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create-competition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCompetition"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register-competitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterCompetitor"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/withdraw-competitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WithdrawCompetitor"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draw-phase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DrawPhase"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prescribe-draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PrescribeDraw"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accept-draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptDraw"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reject-draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RejectDraw"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bind-parameter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BindParameter"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/declare-instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeclareInstruments"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/correct-instrument-declaration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CorrectInstrumentDeclaration"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/complete-task-round": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteTaskRound"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reopen-task-round": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReopenTaskRound"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annul-task-round": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnnulTaskRound"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finalise-competition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FinaliseCompetition"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record-competition-penalty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordCompetitionPenalty"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/append-reflight-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AppendReflightGroup"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assign-group-spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignGroupSpots"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record-reflight-ruling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordReflightRuling"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record-tie-break-outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordTieBreakOutcome"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/define-scoring-team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DefineScoringTeam"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/define-protection-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DefineProtectionGroup"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assign-scoring-team-membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignScoringTeamMembership"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clear-scoring-team-membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClearScoringTeamMembership"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/add-protection-group-member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddProtectionGroupMember"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remove-protection-group-member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RemoveProtectionGroupMember"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configure-team-classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfigureTeamClassification"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-entry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpenEntry"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-flight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpenFlight"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capture-measurement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CaptureMeasurement"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/amend-measurement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AmendMeasurement"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annul-entry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnnulEntry"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record-entry-penalty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordEntryPenalty"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Email?: string;
                    Name?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/person": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    Id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/who-am-i": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/class-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Name?: string;
                    ActiveOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/class-definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    ContentHash: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    OnOrAfter?: string;
                    ClassContentHash?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    Id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competition-event-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    Id: string;
                    IncludePayload?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    CompetitionRef: string;
                    PhaseOrdinal?: number | string;
                    RoundOrdinal?: number | string;
                    TaskRoundOrdinal?: number | string;
                    GroupRef?: string;
                    CompetitorRef?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-round-recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    CompetitionRef: string;
                    PhaseOrdinal: number | string;
                    RoundOrdinal: number | string;
                    TaskRoundOrdinal: number | string;
                    GroupRef?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-round-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    CompetitionRef: string;
                    PhaseOrdinal: number | string;
                    RoundOrdinal: number | string;
                    TaskRoundOrdinal: number | string;
                    GroupRef?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competition-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    CompetitionRef: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competition-pending-tie-breaks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    CompetitionRef: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competition-teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    CompetitionRef: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competition-team-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    CompetitionRef: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draw-diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    CompetitionRef: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptDraw: {
            competitionId: components["schemas"]["CompetitionId"];
        };
        AddProtectionGroupMember: {
            competitionRef: components["schemas"]["CompetitionId"];
            competitorRef: components["schemas"]["CompetitorId"];
            groupRef: components["schemas"]["ProtectionGroupId"];
        };
        AmendMeasurement: {
            entryRef: components["schemas"]["EntryId"];
            /** Format: int32 */
            flightSequence: number | string;
            metric: string;
            newValue: components["schemas"]["MeasuredValue"];
            reason: string;
            by: string;
            instrument?: null | string;
            /** @default false */
            changeInstrument: boolean;
        };
        AnnulEntry: {
            entryRef: components["schemas"]["EntryId"];
            reason: string;
            by: string;
        };
        AnnulTaskRound: {
            competitionRef: components["schemas"]["CompetitionId"];
            /** Format: int32 */
            phaseOrdinal: number | string;
            /** Format: int32 */
            roundOrdinal: number | string;
            /** Format: int32 */
            taskRoundOrdinal: number | string;
            reason: string;
        };
        AppendReflightGroup: {
            competitionRef: components["schemas"]["CompetitionId"];
            /** Format: int32 */
            phaseOrdinal: number | string;
            /** Format: int32 */
            roundOrdinal: number | string;
            /** Format: int32 */
            taskRoundOrdinal: number | string;
            members: components["schemas"]["CompetitorId"][];
            reason: string;
        };
        AssignGroupSpots: {
            competitionRef: components["schemas"]["CompetitionId"];
            /** Format: int32 */
            phaseOrdinal: number | string;
            /** Format: int32 */
            roundOrdinal: number | string;
            /** Format: int32 */
            taskRoundOrdinal: number | string;
            groupRef: components["schemas"]["GroupId"];
            spots: components["schemas"]["GroupSpot"][];
        };
        AssignScoringTeamMembership: {
            competitionRef: components["schemas"]["CompetitionId"];
            competitorRef: components["schemas"]["CompetitorId"];
            teamRef: components["schemas"]["ScoringTeamId"];
            contributes: boolean;
        };
        Band: {
            from: null | components["schemas"]["NumberOrParam"];
            to: null | components["schemas"]["NumberOrParam"];
            /** Format: double */
            ratePerUnit: number | string;
        };
        BindIdentity: {
            personRef: components["schemas"]["PersonId"];
            provider: string;
            subject: string;
        };
        BindParameter: {
            competitionRef: components["schemas"]["CompetitionId"];
            parameterName: string;
            value: components["schemas"]["MeasuredValue"];
            by: string;
            /** Format: int32 */
            phaseOrdinal?: null | number | string;
            /** Format: int32 */
            roundOrdinal?: null | number | string;
        };
        /** @enum {unknown} */
        CapScope: "PerFlight" | "PerTask";
        CaptureMeasurement: {
            entryRef: components["schemas"]["EntryId"];
            /** Format: int32 */
            flightSequence: number | string;
            metric: string;
            value: components["schemas"]["MeasuredValue"];
            instrument?: null | string;
        };
        CapturePolicy: {
            mode: components["schemas"]["CapturePolicyMode"];
            capturers: components["schemas"]["PersonId"][];
        };
        /** @enum {unknown} */
        CapturePolicyMode: "OrganisersOnly" | "AnyRegisteredPerson" | "AllowList";
        ChangePersonClubAffiliation: {
            id: components["schemas"]["PersonId"];
            club: null | components["schemas"]["ClubAffiliation"];
        };
        ChangePersonContactDetails: {
            id: components["schemas"]["PersonId"];
            contact: components["schemas"]["ContactDetails"];
        };
        ClassDefinition: {
            name: string;
            faiDesignation?: null | string;
            version: string;
            finalRanking?: null | components["schemas"]["FinalRankingKind"];
            parameters?: components["schemas"]["Parameter"][];
            reflight: components["schemas"]["ReflightRule"];
            penalties?: components["schemas"]["PenaltyDefinition"][];
            phases: components["schemas"]["PhaseDefinition"][];
        };
        ClearScoringTeamMembership: {
            competitionRef: components["schemas"]["CompetitionId"];
            competitorRef: components["schemas"]["CompetitorId"];
        };
        ClubAffiliation: {
            clubName: string;
            membershipNumber?: null | string;
        };
        /** @enum {unknown} */
        Comparator: "LessThan" | "LessOrEqual" | "GreaterThan" | "GreaterOrEqual" | "EqualTo";
        CompetitionId: {
            /** Format: uuid */
            value?: string;
        };
        CompetitorId: {
            /** Format: uuid */
            value?: string;
        };
        CompleteTaskRound: {
            competitionRef: components["schemas"]["CompetitionId"];
            /** Format: int32 */
            phaseOrdinal: number | string;
            /** Format: int32 */
            roundOrdinal: number | string;
            /** Format: int32 */
            taskRoundOrdinal: number | string;
        };
        /** @enum {unknown} */
        CompositionKind: "FixedSequence" | "ChooseFromCatalogue";
        ConfigureCapturePolicy: {
            competitionRef: components["schemas"]["CompetitionId"];
            policy: components["schemas"]["CapturePolicy"];
        };
        ConfigureTeamClassification: {
            competitionRef: components["schemas"]["CompetitionId"];
            enabled: boolean;
            by: string;
        };
        ContactDetails: {
            email: string;
            phone?: null | string;
            homeCity?: null | string;
        };
        CorrectInstrumentDeclaration: {
            competitionRef: components["schemas"]["CompetitionId"];
            instruments: components["schemas"]["DeclaredInstrument"][];
            reason: string;
            by: string;
        };
        CreateCompetition: {
            name: string;
            location: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            classContentHash: string;
        };
        DeclaredInstrument: {
            instrument: string;
            metric: string;
            scale: components["schemas"]["ReadingScale"];
        };
        DeclareInstruments: {
            competitionRef: components["schemas"]["CompetitionId"];
            instruments: components["schemas"]["DeclaredInstrument"][];
            by: string;
        };
        DefineProtectionGroup: {
            competitionRef: components["schemas"]["CompetitionId"];
            name: string;
        };
        DefineScoringTeam: {
            competitionRef: components["schemas"]["CompetitionId"];
            name: string;
        };
        DrawPhase: {
            competitionId: components["schemas"]["CompetitionId"];
            /** Format: int32 */
            rounds: number | string;
            taskRefs?: null | string[];
        };
        /** @enum {unknown} */
        DropDimension: "ByRound" | "ByTask";
        DropPolicy: {
            dimension: components["schemas"]["DropDimension"];
            /** Format: int32 */
            dropCount: number | string;
            /** Format: int32 */
            applyWhenRoundsCompletedAtLeast?: null | number | string;
            /** Format: int32 */
            applyWhenResultsAtLeast?: null | number | string;
            tieBreak?: components["schemas"]["DropTieBreak"];
        };
        /** @enum {unknown} */
        DropTieBreak: "Latest" | "Earliest";
        EntryId: {
            /** Format: uuid */
            value?: string;
        };
        FinaliseCompetition: {
            competitionRef: components["schemas"]["CompetitionId"];
            by: string;
        };
        /** @enum {unknown} */
        FinalRankingKind: "SinglePhase" | "LastPhaseReplaces" | "SplitByPromotion" | null;
        FlagOrParam: unknown;
        FlightSelection: components["schemas"]["FlightSelectionLastFlight"] | components["schemas"]["FlightSelectionAllFlights"] | components["schemas"]["FlightSelectionLastNFlights"] | components["schemas"]["FlightSelectionBestNFlights"] | components["schemas"]["FlightSelectionExactlyNInOrder"];
        FlightSelectionAllFlights: {
            /** @enum {string} */
            $kind?: "all";
        };
        FlightSelectionBestNFlights: {
            /** @enum {string} */
            $kind?: "bestN";
            /** Format: int32 */
            count: number | string;
            rankByMetric?: null | string;
            targets?: components["schemas"]["TargetAssignment"];
            targetValues?: (number | string)[];
        };
        FlightSelectionExactlyNInOrder: {
            /** @enum {string} */
            $kind?: "exactlyN";
            /** Format: int32 */
            count: number | string;
            targets?: components["schemas"]["TargetAssignment"];
            targetValues?: (number | string)[];
        };
        FlightSelectionLastFlight: {
            /** @enum {string} */
            $kind?: "last";
        };
        FlightSelectionLastNFlights: {
            /** @enum {string} */
            $kind?: "lastN";
            /** Format: int32 */
            count: number | string;
        };
        GrantRole: {
            personRef: components["schemas"]["PersonId"];
            role: components["schemas"]["PersonRole"];
        };
        GroupConstraint: {
            minPerGroup: components["schemas"]["NumberOrParam"];
            /** Format: int32 */
            minValidResults?: null | number | string;
            minEnforcement?: null | components["schemas"]["MinEnforcement"];
        };
        GroupId: {
            /** Format: uuid */
            value?: string;
        };
        GroupSpot: {
            competitorRef: components["schemas"]["CompetitorId"];
            /** Format: int32 */
            spot: number | string;
        };
        LinkSignIn: Record<string, never>;
        LookupRow: {
            /** Format: double */
            upTo: null | number | string;
            /** Format: double */
            points: number | string;
        };
        /** @enum {unknown} */
        MeasuredKind: "Number" | "Flag";
        MeasuredValue: {
            kind: components["schemas"]["MeasuredKind"];
            /** Format: double */
            number?: null | number | string;
            flag?: null | boolean;
        };
        MetricDefinition: {
            name: string;
            kind: components["schemas"]["MeasuredKind"];
            unit?: null | string;
            declaredBeforeLaunch?: boolean;
            precision?: null | components["schemas"]["Rounding"];
            whenNotRecorded?: null | components["schemas"]["MeasuredValue"];
        };
        /** @enum {unknown} */
        MinEnforcement: "Shall" | "Should" | null;
        Normalisation: {
            direction: components["schemas"]["NormalisationDirection"];
            /** Format: int32 */
            winnerScore: number | string;
            round?: null | components["schemas"]["Rounding"];
        };
        /** @enum {unknown} */
        NormalisationDirection: "HigherIsBetter" | "LowerIsBetter";
        NumberOrParam: unknown;
        OpenEntry: {
            competitionRef: components["schemas"]["CompetitionId"];
            /** Format: int32 */
            phaseOrdinal: number | string;
            /** Format: int32 */
            roundOrdinal: number | string;
            /** Format: int32 */
            taskRoundOrdinal: number | string;
            groupRef: components["schemas"]["GroupId"];
            competitorRef: components["schemas"]["CompetitorId"];
            role?: components["schemas"]["ReflightRole"];
            /** Format: int32 */
            countsForRoundOrdinal?: null | number | string;
            reason?: null | string;
        };
        OpenFlight: {
            entryRef: components["schemas"]["EntryId"];
            /** Format: int32 */
            sequence?: null | number | string;
        };
        Parameter: {
            name: string;
            kind?: components["schemas"]["MeasuredKind"];
            unit?: null | string;
            defaultValue?: null | components["schemas"]["MeasuredValue"];
            allowedValues?: components["schemas"]["MeasuredValue"][];
            boundAt?: components["schemas"]["ParameterBindingPoint"];
        };
        /** @enum {unknown} */
        ParameterBindingPoint: "CompetitionSetup" | "BeforeFlying" | "PerRound";
        /** @enum {unknown} */
        PenaltyAccrual: "OncePerAttempt" | "PerOccurrence";
        PenaltyDefinition: {
            infractionType: string;
            exclusionGroups?: string[];
            accrual?: components["schemas"]["PenaltyAccrual"];
            effects: components["schemas"]["PenaltyEffectSpec"][];
            permittedScopes?: null | components["schemas"]["PenaltyScope"][];
        };
        /** @enum {unknown} */
        PenaltyEffect: "DeductPoints" | "ZeroFlight" | "ZeroRound" | "ZeroTask" | "Disqualify";
        PenaltyEffectSpec: {
            effect: components["schemas"]["PenaltyEffect"];
            /** Format: double */
            points?: null | number | string;
        };
        /** @enum {unknown} */
        PenaltyScope: "Flight" | "Entry" | "TaskRound" | "Competition";
        PersonId: {
            /** Format: uuid */
            value?: string;
        };
        /** @enum {unknown} */
        PersonRole: "Competitor" | "Organiser";
        PhaseDefinition: {
            /** Format: int32 */
            ordinal: number | string;
            type: components["schemas"]["PhaseType"];
            rounds?: components["schemas"]["RoundComposition"];
            validity: components["schemas"]["ValidityRule"];
            drops?: components["schemas"]["DropPolicy"][];
            tieBreaks?: components["schemas"]["TieBreakDirective"][];
            promotion?: null | components["schemas"]["PromotionRule"];
            tasks: components["schemas"]["TaskDefinition"][];
        };
        /** @enum {unknown} */
        PhaseType: "Preliminary" | "Flyoff";
        Predicate: components["schemas"]["PredicateComparison"] | components["schemas"]["PredicateAllOf"] | components["schemas"]["PredicateIsRecorded"];
        PredicateAllOf: {
            /** @enum {string} */
            $kind?: "allOf";
            children: components["schemas"]["Predicate"][];
        };
        PredicateComparison: {
            /** @enum {string} */
            $kind?: "comparison";
            leftMetricRef: string;
            op: components["schemas"]["Comparator"];
            rightMetricRef?: null | string;
            rightValue?: null | components["schemas"]["MeasuredValue"];
        };
        PredicateIsRecorded: {
            /** @enum {string} */
            $kind?: "isRecorded";
            metricRef: string;
        };
        PrescribedGroup: {
            competitors: components["schemas"]["CompetitorId"][];
        };
        PrescribeDraw: {
            competitionId: components["schemas"]["CompetitionId"];
            rounds: components["schemas"]["PrescribedRound"][];
            by: string;
        };
        PrescribedRound: {
            taskRef: null | string;
            groups: components["schemas"]["PrescribedGroup"][];
        };
        /** @enum {unknown} */
        PromotionKind: "TopN" | "TopPercent";
        PromotionRule: {
            kind: components["schemas"]["PromotionKind"];
            topN?: null | components["schemas"]["NumberOrParam"];
            /** Format: double */
            topPercent?: null | number | string;
            minGroupSize?: null | components["schemas"]["NumberOrParam"];
            maxGroupSize?: null | components["schemas"]["NumberOrParam"];
            carryPenalties?: null | components["schemas"]["FlagOrParam"];
        };
        ProtectionGroupId: {
            /** Format: uuid */
            value?: string;
        };
        PublishClassDefinition: {
            definition: components["schemas"]["ClassDefinition"];
        };
        ReadingScale: {
            unit: string;
            marks: components["schemas"]["ScaleMark"][];
            /** Format: double */
            offScaleReading?: null | number | string;
            readingSet?: (number | string)[];
        };
        RecordCompetitionPenalty: {
            competitionRef: components["schemas"]["CompetitionId"];
            infractionType: string;
            scope: components["schemas"]["PenaltyScope"];
            competitorRef: components["schemas"]["CompetitorId"];
            taskRound: null | components["schemas"]["TaskRoundCoordinate"];
            by: null | string;
        };
        RecordEntryPenalty: {
            entryRef: components["schemas"]["EntryId"];
            infractionType: string;
            scope: components["schemas"]["PenaltyScope"];
            by: null | string;
        };
        RecordReflightRuling: {
            competitionRef: components["schemas"]["CompetitionId"];
            /** Format: int32 */
            phaseOrdinal: number | string;
            /** Format: int32 */
            roundOrdinal: number | string;
            /** Format: int32 */
            taskRoundOrdinal: number | string;
            competitorRef: components["schemas"]["CompetitorId"];
            selection: components["schemas"]["ReflightSelection"];
            reason: string;
            by: null | string;
        };
        RecordTieBreakOutcome: {
            competitionRef: components["schemas"]["CompetitionId"];
            /** Format: int32 */
            phaseOrdinal: number | string;
            directive: components["schemas"]["TieBreakDirective"];
            placings: components["schemas"]["TieBreakOutcomePlacing"][];
            reason: string;
            by?: null | string;
        };
        /**
         * @default Original
         * @enum {unknown}
         */
        ReflightRole: "Original" | "Entitled" | "Filler";
        ReflightRule: {
            entitledScores: components["schemas"]["ReflightSelection"];
            othersScore: components["schemas"]["ReflightSelection"];
            minNewGroupSize?: null | components["schemas"]["NumberOrParam"];
        };
        /** @enum {unknown} */
        ReflightSelection: "Replacement" | "BetterOf" | "NotPermitted" | "UndefinedRequiresRuling";
        RegisterCompetitor: {
            competitionId: components["schemas"]["CompetitionId"];
            personId: components["schemas"]["PersonId"];
        };
        RegisterPerson: {
            name: string;
            contact: components["schemas"]["ContactDetails"];
            club: null | components["schemas"]["ClubAffiliation"];
        };
        RejectDraw: {
            competitionRef: components["schemas"]["CompetitionId"];
            reason: string;
        };
        RemoveProtectionGroupMember: {
            competitionRef: components["schemas"]["CompetitionId"];
            competitorRef: components["schemas"]["CompetitorId"];
            groupRef: components["schemas"]["ProtectionGroupId"];
        };
        RenamePerson: {
            id: components["schemas"]["PersonId"];
            name: string;
        };
        ReopenTaskRound: {
            competitionRef: components["schemas"]["CompetitionId"];
            /** Format: int32 */
            phaseOrdinal: number | string;
            /** Format: int32 */
            roundOrdinal: number | string;
            /** Format: int32 */
            taskRoundOrdinal: number | string;
            reason: string;
        };
        RevokeRole: {
            personRef: components["schemas"]["PersonId"];
            role: components["schemas"]["PersonRole"];
        };
        RoundComposition: {
            kind?: components["schemas"]["CompositionKind"];
            /** Format: int32 */
            tasksPerRound?: number | string;
            requireDistinctTaskPerRound?: boolean;
            /** Format: int32 */
            maxRounds?: null | number | string;
        };
        Rounding: {
            mode: components["schemas"]["RoundingMode"];
            /** Format: double */
            precision: number | string;
        };
        /** @enum {unknown} */
        RoundingMode: "Truncate" | "HalfUp" | "Ceiling";
        ScaleMark: {
            /** Format: double */
            upTo: number | string;
            /** Format: double */
            reading: number | string;
        };
        ScoreTerm: components["schemas"]["ScoreTermRateTerm"] | components["schemas"]["ScoreTermLookupTerm"] | components["schemas"]["ScoreTermPiecewiseTerm"] | components["schemas"]["ScoreTermConstantTerm"] | components["schemas"]["ScoreTermConditionalTerm"];
        ScoreTermConditionalTerm: {
            /** @enum {string} */
            $kind?: "conditional";
            when: components["schemas"]["Predicate"];
            then: components["schemas"]["ScoreTerm"];
            else?: null | components["schemas"]["ScoreTerm"];
        };
        ScoreTermConstantTerm: {
            /** @enum {string} */
            $kind?: "constant";
            /** Format: double */
            value: number | string;
        };
        ScoreTermLookupTerm: {
            /** @enum {string} */
            $kind?: "lookup";
            metricRef: string;
            rows: components["schemas"]["LookupRow"][];
        };
        ScoreTermPiecewiseTerm: {
            /** @enum {string} */
            $kind?: "piecewise";
            metricRef: string;
            origin?: null | components["schemas"]["NumberOrParam"];
            bands: components["schemas"]["Band"][];
        };
        ScoreTermRateTerm: {
            /** @enum {string} */
            $kind?: "rate";
            metricRef: string;
            /** Format: double */
            rate: number | string;
            cap?: null | components["schemas"]["NumberOrParam"];
            capScope?: components["schemas"]["CapScope"];
        };
        ScoringTeamId: {
            /** Format: uuid */
            value?: string;
        };
        /** @enum {unknown} */
        TargetAssignment: "None" | "AnyOrder" | "InOrder";
        TaskDefinition: {
            code: string;
            name: string;
            metrics: components["schemas"]["MetricDefinition"][];
            flights: components["schemas"]["FlightSelection"];
            timing: components["schemas"]["TaskTiming"];
            group?: null | components["schemas"]["GroupConstraint"];
            normalise?: null | components["schemas"]["Normalisation"];
            validWhen?: null | components["schemas"]["Predicate"];
            flightValidWhen?: null | components["schemas"]["Predicate"];
            rawScore?: null | components["schemas"]["Rounding"];
            reflight?: null | components["schemas"]["ReflightRule"];
            score: components["schemas"]["ScoreTerm"][];
            scoreNormalised?: components["schemas"]["ScoreTerm"][];
        };
        TaskRoundCoordinate: {
            /** Format: int32 */
            phaseOrdinal: number | string;
            /** Format: int32 */
            roundOrdinal: number | string;
            /** Format: int32 */
            taskRoundOrdinal: number | string;
        };
        TaskTiming: {
            kind: components["schemas"]["WorkingTimeKind"];
            workingTime?: null | components["schemas"]["NumberOrParam"];
            preparationTime?: null | components["schemas"]["NumberOrParam"];
            maxLaunches?: null | components["schemas"]["NumberOrParam"];
        };
        TieBreakDirective: components["schemas"]["TieBreakDirectiveBestDroppedScore"] | components["schemas"]["TieBreakDirectiveQualifyingPosition"] | components["schemas"]["TieBreakDirectiveAdditionalFullRound"] | components["schemas"]["TieBreakDirectiveTieBreakFlyoff"] | components["schemas"]["TieBreakDirectiveClassificationRounds"] | components["schemas"]["TieBreakDirectiveEqualPlaces"] | components["schemas"]["TieBreakDirectiveUndefinedRequiresRuling"];
        TieBreakDirectiveAdditionalFullRound: {
            /** @enum {string} */
            $kind?: "additionalFullRound";
        };
        TieBreakDirectiveBestDroppedScore: {
            /** @enum {string} */
            $kind?: "bestDroppedScore";
        };
        TieBreakDirectiveClassificationRounds: {
            /** @enum {string} */
            $kind?: "classificationRounds";
        };
        TieBreakDirectiveEqualPlaces: {
            /** @enum {string} */
            $kind?: "equalPlaces";
        };
        TieBreakDirectiveQualifyingPosition: {
            /** @enum {string} */
            $kind?: "qualifyingPosition";
            /** Format: int32 */
            sourcePhaseOrdinal: number | string;
        };
        TieBreakDirectiveTieBreakFlyoff: {
            /** @enum {string} */
            $kind?: "tiebreakFlyoff";
        };
        TieBreakDirectiveUndefinedRequiresRuling: {
            /** @enum {string} */
            $kind?: "undefinedRequiresRuling";
        };
        TieBreakOutcomePlacing: {
            competitorRef: components["schemas"]["CompetitorId"];
            /** Format: int32 */
            placeInGroup: number | string;
        };
        ValidityRule: {
            minRounds: components["schemas"]["NumberOrParam"];
            /** Format: int32 */
            minTasks?: null | number | string;
        };
        WithdrawCompetitor: {
            competitionId: components["schemas"]["CompetitionId"];
            competitorId: components["schemas"]["CompetitorId"];
        };
        /** @enum {unknown} */
        WorkingTimeKind: "Fixed" | "UntilAllFlightsComplete";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
